#!/bin/sh

# there are other ACTIONs like ifupdate we don't need
case "$ACTION" in
	ifup)					# OpenWrt gives a network, not a phys. Interface
		/etc/init.d/ddns enabled && /usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- start
		;;
	ifdown)
		/usr/lib/ddns/dynamic_dns_updater.sh -n "$INTERFACE" -- stop
		;;
esac
